---
title: "strings_factors"
author: "Hana Akbarnejad"
date: "10/15/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(p8105.datasets)

```

## string manipulation

```{r}

string_vec = c("my", "name", "is", "jeff")
string_vec

str_detect(string_vec, "jeff")
str_detect(string_vec, "m")

str_replace(string_vec, "jeff","Jeff")
str_replace(string_vec, "m", "M")
```

using str, there are a lot of str stuff in R. everything in stringr package start with str_. 
str_detect(): tell me whether of not this string exists in this vetor. gives T or F.
str_replace(): 

```{r}

string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think$")
str_detect(string_vec, "^i think")
```

^ starts with and ends with $

```{r}

string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )

str_detect(string_vec, "[Bb]ush")
```

 strings which contain this or this [Bb]
 
```{r}

string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "[0-9][a-zA-Z]")
```
 
## patterns

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.11")
```

dot(.) matches characters, placeholders and stuff

```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )

str_detect(string_vec, "\\[")
```

